# Generated by Django 5.2 on 2025-05-05 17:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(max_length=30)),
                ('gear_type', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto'), ('hybrid', 'Hybrid')], default='manual', max_length=10)),
                ('distance_covered', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1986), django.core.validators.MaxValueValidator(2000)])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
